title: Melati Putri Santika
logo: /assets/img/logo.png
description: I am an Undergraduate Statistics Student at Diponegoro University. 
<br> <br>
I am currrently a Data Analytics student at MSIB Zenius.
<br> <br>
<a href="https://www.linkedin.com/in/melati-putri-santika-027bb8207/">LinkedIn</a>
show_downloads: true
theme: jekyll-theme-minimal
