title: <p align="center"> Melati Putri Santika </p>

logo: "/images/foto.jpeg?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/melati-putri-santika-027bb8207/">LinkedIn</a> |
  <a href="https://github.com/melatiptrs">GitHub</a>
  </p>
  
  <p align="justify">
  I am an Undergraduate Statistics Student at Diponegoro University.
  <br><br>
  I am currrently a Data Analytics student at MSIB Zenius.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
